### ISSUE TITLE
Design Website

### ISSUE THREAD

**Issue by andytudhope** [status-im/ETHPrize#1]
This is a bounty to design both the ETHPrize website and the ETHPrize logo.

A photo of a (very rough) wireframe is attached. Basically, you have free rein to design a simple one page website that will give some info about what ETHPrize is all about, what prizes are on on offer and what their associated values are. That said, this page needs to capture the open, inclusive, technology-focussed, and community-based nature of both Ethereum and this initiative to improve core tooling.

ETHPrize is working to identify the most critical issues facing ethereum developers through a community research project being led by Truebit, Status, L4 and others. We have been interviewing +100 dapp teams / developers about common challenges in developing on ethereum, missing tools, other issues, etc.

Additional information will be provided in terms of copy and what ETHPrize is all about to the designer that is chosen.

Submissions need to take the form of Zeppelin or Invision links (or some other appropriate design platform that developers can work quickly and easily off). The design needs to be responsive and look good on mobile too.

An example of the general quality and design language we aim for can be found [here](https://github.com/status-im/open-bounty/issues/183#issuecomment-360134513). Use this and the wireframe (with some added images/designs that make it pop) as a template to base your design off.

Please comment below this issue with a portfolio link indicating interest and perhaps a less rough sketch of what you envision. A designer will be chosen and the bounty will be locked for that person.

![img_1391](https://user-images.githubusercontent.com/13001517/36862051-69305102-1d8e-11e8-8736-5c8bf4db39ee.JPG)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8db59dea8a40dd05bffa0606473b95d2d0f97e0f02a981b49c586ba362e1aaa2](https://etherscan.io/tx/0x8db59dea8a40dd05bffa0606473b95d2d0f97e0f02a981b49c586ba362e1aaa2)

**Comment by fshkliarau** [comment]
Hey Andy,
thank you for creating this bounty, sounds interesting.

Here's my portfolio website: http://fedor.design/

I'd love to learn more about the bounty, goals and challenges for this website.

Cheers,
Fedor

**Comment by andytudhope** [comment]
@fshkliarau awesome - this looks great. Thanks for stepping up. As Denis knows you, and you have a clearly good site, I am happy to lock this bounty for you. I will get your email and we can communicate further there. This bounty is now locked.
