### ISSUE TITLE
bounties report - interviews vs. analysis

### ISSUE THREAD

**Issue by youarentryan** [status-im/ETHPrize#17]
Can you help me understand the difference between these folders?

This project is brilliant by the way. Really excited to dig through the interview notes!

**Comment by Haseeb-Qureshi** [comment]
Maybe a dumb question: are the interviews hosted somewhere on the Ethprize site, or only in the repo?

**Comment by mkosowsk** [comment]
@youarentryan thanks! The `bounties_report/analysis` folder contains all the interviews in .txt format while the `bounties_report/interviews` contains all the the interviews in HTML which will eventually live on the ETHPrize site. We recommend you do data analysis on the .txt files unless you're a glutton for punishment 😂

@Haseeb-Qureshi great to have you on this repo! And of course no such thing as a dumb question :P Currently the interviews only live here but will also eventually be hosted on http://ethprize.io/ along with a [report that summarizes findings](https://github.com/status-im/ETHPrize/issues/13). This is a current work in progress.

Haseeb, I know that you're one for data so this [ETHPrize dev interviews analysis on Kaggle](https://www.kaggle.com/mratsim/state-of-the-art-nlp-on-ethereum-dev-interviews) may be interesting to you as well 👍🏻

**Comment by youarentryan** [comment]
Thanks @mkosowsk . Really really awesome work!

**Comment by mkosowsk** [comment]
@youarentryan I would love to take credit! But the excellent @andytudhope has done the leg work here 😀
