### ISSUE TITLE
Build Website

### ISSUE THREAD

**Issue by andytudhope** [status-im/ETHPrize#3]
Use the template designed by Fedor in #1 and build it.

It is a simple one page website and we need it built by the 10th of March, so there is some time pressure on this bounty. 

The site needs to be mobile responsive and further context and copy will be provided to the person/people who agree to take this on.

## Links
1. [Figma](https://www.figma.com/file/FCakALK84WSxZB5QhvaV213e/ETHPrize?node-id=1%3A2) - The latest design version of the website. If you switch to "Code" view on the upper right corner, you can see the some of the specs. "Learn more" on the first screen is an anchor link to the About section. Links at the very bottom: Fedor Shkliarau (http://fedor.design/), Scott Webb (https://unsplash.com/@scottwebb)

2. [Readymag](https://readymag.com/shkliarau/995140/) - Prototype with animation how the effect of the effect from Tympanus and overall behavior.

3. [Tympanus](https://tympanus.net/Tutorials/CSSMaskTransition/index2.html) - effect for the hero image and second image in About section.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9c925f2389c842ebc5210df49ed453a6d0ef344dcecb792e93d8a54c03e9b442](https://etherscan.io/tx/0x9c925f2389c842ebc5210df49ed453a6d0ef344dcecb792e93d8a54c03e9b442)

**Comment by andytudhope** [comment]
@wswidzinski and @maciejmatu any chance you would be willing to take on this quick job?

**Comment by CS76** [comment]
Is it still open ??

**Comment by CS76** [comment]
@andytudhope Can you provide the design copy and the context, please? Thanks.

**Comment by CS76** [comment]
Sure, I'm on it. BTW the Figma designs showcase a different set of logos and the prototype has a different one. Have you decided any one of those? We can also try all of them once the design is ready.

**Comment by fshkliarau** [comment]
Hey all,
here's the final logo which you can also find in the Figma file. (Please refer to the prototype only in terms of the scrolling behavior and animations)
![logo color](https://user-images.githubusercontent.com/36989545/37168144-395017da-2304-11e8-9f5c-7b1ad2071721.png)
