### ISSUE TITLE
Build New Design and Modals

### ISSUE THREAD

**Issue by andytudhope** [status-im/ETHPrize#8]
Fedor has updated some of the design for the site and added some really cool modal boxes for extra information on each bounty when you click the `Learn More` button.

Now we just need to build it. @CS76 are you able to do this before next week Monday if possible?

The new designs can be found [here](https://www.figma.com/file/FCakALK84WSxZB5QhvaV213e/ETHPrize?node-id=1%3A2).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3d7e7c6bf2ecb92c301987fd0a150e920e5271ce07f129a903a617baf161ac60](https://etherscan.io/tx/0x3d7e7c6bf2ecb92c301987fd0a150e920e5271ce07f129a903a617baf161ac60)

**Comment by CS76** [comment]
@andytudhope Sure sounds good. I'm on it 👍
